apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-nginx-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: nginx
    newTag: alpine    # ex : nginx:alpine en DEV

patchesStrategicMerge:
  - configmap-dev.yaml
  - service-dev.yaml
