apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-nginx-dev

resources:
  - ../../base
  - namespace-dev.yaml

patches:
  - path: configmap-dev.yaml
  - path: deployment-dev.yaml
  - path: service-dev.yaml
