apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-nginx-prod

resources:
  - ../../base
  - namespace.yaml

images:
  - name: nginx
    newTag: stable   # PROD : nginx:stable, comme ta base

patchesStrategicMerge:
  - configmap-prod.yaml
  - service-prod.yaml
