apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-nginx-prod

resources:
  - ../../base
  - namespace-prod.yaml

patches:
  - path: configmap-prod.yaml
  - path: deployment-prod.yaml
  - path: service-prod.yaml
